name: Deploy MkDocs

on:
  push:
    branches:
      - gh-pages  # Ou a branch que você está utilizando

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install mkdocs mkdocs-material

      - name: Construir site
        run: mkdocs build

      - name: Upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: site  # Pasta gerada pelo MkDocs

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4
